### ISSUE TITLE
attribute "tabindex" has invalid value "-1"

### ISSUE THREAD

**Issue by subhaze** [geoffmcl/tidy-fork#9]
tabindex should allow for an optional `-` prefixed integer.

http://www.w3.org/TR/html5/editing.html#sequential-focus-navigation-and-the-tabindex-attribute
http://www.w3.org/TR/html5/infrastructure.html#valid-integer

**Comment by geoffmcl** [comment]
Hi Michael,

This should now be fixed in the geoffmcl-restart
branch -
$ git checkout geoffmcl-restart

If you get a chance to check and advise
would be appreciated...

Regards,
Geoff.

**Comment by subhaze** [comment]
You can now prefix integers with `-` however, it seems you can now add non-integers as well.

**Comment by geoffmcl** [comment]
Hi Michael (alias=subhaze),

Hmmm, my fix was VERY simple... re-lined to
just to avoid line wrap...

     /* tabindex may be preceeded by - */
     if (attval->attribute &&
         (strcmp(attval->attribute,"tabindex") == 0)
         && (*p == '-'))
         ++p;

and then it does (re-lined a little for brevity) -
     while (*p) {
         if (!TY_(IsDigit)(*p)) {
             TY_(ReportAttrError)( doc, node,
                 attval, BAD_ATTRIBUTE_VALUE);
             break;
         }
         ++p;
     }

Now MAYBE 'IsDigit' accepts MORE than pure digits,
then that needs to be 'fixed'. But it does not look
likely...

In lexer.c IsDigit(uint c) does -
     uint map = MAP(c);
     return (map & digit) != 0;

If still a problem, please test again and give me
an simple example test case that fails...

But even if it does fail, then please close this '-'
issue and open another, with a sample case... since
this is a different, older, read in 'base' tidy,
problem...

Thanks for your efforts, time, and reports...

Regards,
Geoff.

**Comment by subhaze** [comment]
@geoffmcl OK, after recompiling and using a small HTML everything was well. I think the issue was on my end having not updated the tidy5 bin being used in my Makefile. Sorry for the confusion, and thanks!
